defaults:
  - paired/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 2e5 # divided between training ego, conf-br, and conf-eg
LR: 1e-4
CLIP_EPS: 0.1
ENT_COEF: 0.01
