defaults:
  - rotate_without_pop/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 1e4 # per iter of open-ended training, divided between 4 types of rollouts and all partner seeds
TIMESTEPS_PER_ITER_EGO: 1e4
NUM_OPEN_ENDED_ITERS: 10
REGRET_SP_WEIGHT: 2.0 # weight on the SP term in the perstep regret loss
LR: 1e-4
CLIP_EPS: 0.1
ENT_COEF: 0.01
ANNEAL_LR: true
EGO_ARGS:
  LR: 5e-5
  ENT_COEF: 1e-4
  CLIP_EPS: 0.1
  ANNEAL_LR: false
  UPDATE_EPOCHS: 10
  S5_D_MODEL: 128
  S5_SSM_SIZE: 128
  S5_ACTOR_CRITIC_HIDDEN_DIM: 1024
  FC_N_LAYERS: 3
