defaults:
  - rotate/_base_
  - _self_ # values from this file override the values from the base file

TIMESTEPS_PER_ITER_PARTNER: 1e7 # per iter of open-ended training, divided between conf-br and conf-ego and between all partner seeds
TIMESTEPS_PER_ITER_EGO: 2e6
NUM_OPEN_ENDED_ITERS: 30
REGRET_SP_WEIGHT: 2.0 # weight on the SP term in the perstep regret loss
LR: 1e-4
CLIP_EPS: 0.1
ENT_COEF: 0.01
ANNEAL_LR: true
EGO_ARGS:
  LR: 5e-5
  ENT_COEF: 1e-4
  CLIP_EPS: 0.1
  ANNEAL_LR: false
  UPDATE_EPOCHS: 10
  S5_D_MODEL: 64 # 128
  S5_SSM_SIZE: 64 # 128
  S5_ACTOR_CRITIC_HIDDEN_DIM: 256 # 1024
  FC_N_LAYERS: 3
PRETRAIN_ARGS:
  TOTAL_TIMESTEPS: 1e6 # timesteps to split between IPPO partners
  NUM_AGENTS: 3 # number of IPPO partners to pretrain
  NUM_CHECKPOINTS: 2 # number of checkpoints to save for each IPPO partner