defaults:
  - task: lbf # task configs
  - algorithm@algorithm: ippo/${task} # task-specific algorithm configs
  - hydra: hydra_simple
  - _self_

ENV_NAME: ${task.ENV_NAME}
ENV_KWARGS: ${task.ENV_KWARGS}
ROLLOUT_LENGTH: ${task.ROLLOUT_LENGTH}
TASK_NAME: ${task.TASK_NAME}

algorithm:
  NUM_SEEDS: 4
  TRAIN_SEED: 20374
  ENV_NAME: ${ENV_NAME}
  ENV_KWARGS: ${ENV_KWARGS}
  ROLLOUT_LENGTH: ${ROLLOUT_LENGTH}

label: "default_label"
name: ${TASK_NAME}/${algorithm.ALG}/${label}

# wandb settings
logger: 
  project: open-ended-aht
  entity: aht-project
  tags: 
    - ${algorithm.ALG}
    - ${TASK_NAME}
    - seed=${algorithm.TRAIN_SEED}
    - ${label}
  mode: offline # options: online, offline, disabled
  verbose: false
  log_train_out: true # whether to log the out dictionary
  log_eval_out: true # whether to log the eval metrics

# Local logger
local_logger:
  save_train_out: true
  save_eval_out: true
