# @package algorithm
# ^ tells hydra to place these value directly under algorithm key
ALG: ippo
TOTAL_TIMESTEPS: 5e5
TRAIN_CHUNKS: 10
ACTOR_TYPE: s5
NUM_CHECKPOINTS: 5
GAMMA: 0.999
GAE_LAMBDA: 0.95
VF_COEF: 0.5
MAX_GRAD_NORM: 1.0
ANNEAL_LR: True

