defaults:
  - ippo/_base_
  - _self_ # values from this file override the values from the base file

TOTAL_TIMESTEPS: 1e10
TRAIN_CHUNKS: 5000
SEED: 12345
LR: .0005
NUM_ENVS: 128
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
CLIP_EPS: 0.03
ENT_COEF: 0.01

S5_D_MODEL: 512
S5_SSM_SIZE: 512
S5_ACTOR_CRITIC_HIDDEN_DIM: 512
FC_N_LAYERS: 3